### ISSUE TITLE
Unify the look of the readme

### ISSUE THREAD

**Issue by makma** [fingerprintjs/fingerprintjs-pro-spa#33]
Add the company logo, format badges, etc.

**Comment by JuroUhlar** [comment]
@makma would you say of this was addressed in https://github.com/fingerprintjs/fingerprintjs-pro-spa/pull/36 ? Or what is missing? thanks!

**Comment by makma** [comment]
Yes, it was @JuroUhlar, thank you

**Comment by makma** [comment]
Fixed in #36
