### ISSUE TITLE
FPJSAgent hasn't loaded yet. Make sure to call the init() method first.

### ISSUE THREAD

**Issue by kdawgwilk** [fingerprintjs/fingerprintjs-pro-spa#54]
We are definitely calling the `init()` method first before calling `getVisitorData` but maybe it has more to do with NextJS SSR and hydration?  We aren't using the react sdk because we need access to the client outside of the react rendering lifcycle for networking to add some headers to requests.

**Comment by JuroUhlar** [comment]
Hi @kdawgwilk, I can think of two possible issues: 

* Make sure you call init with **await**:  `await fpjsClient.init()`. It's an async function that loads the latest fingerprinting logic from our CDN, you must wait for the network request to finish.
* Make sure you are initializing the client and fingerprinting only the client, not on the server or at build time, you can find more information and examples in our documentation: https://dev.fingerprint.com/docs/usage-with-server-side-rendering-frameworks

If none of these resolve the issue, please post an expanded example indicating where in the Next.js lifecycle you are using the Fingerprint agent, thank you!

**Comment by JuroUhlar** [comment]
Closing as answered.
